// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDARst_ht43FSmKcxri39WONqNsr-eS8J8',
    appId: '1:325048551161:web:d7457f3a86d1e4ae504428',
    messagingSenderId: '325048551161',
    projectId: 'test-liitx',
    authDomain: 'test-liitx.firebaseapp.com',
    storageBucket: 'test-liitx.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS1ov2H_on9MUrDdRRCpA5MmdidtbRtUA',
    appId: '1:325048551161:android:3c9b11107bd16f19504428',
    messagingSenderId: '325048551161',
    projectId: 'test-liitx',
    storageBucket: 'test-liitx.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZWv15ZYRzFEjERJOd6xFSy2BEOaWFh5o',
    appId: '1:325048551161:ios:4e0fa5179c6539af504428',
    messagingSenderId: '325048551161',
    projectId: 'test-liitx',
    storageBucket: 'test-liitx.appspot.com',
    iosClientId: '325048551161-9lviretbbngvvpkfnijlt7ppjjjccoiu.apps.googleusercontent.com',
    iosBundleId: 'com.liitx.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZWv15ZYRzFEjERJOd6xFSy2BEOaWFh5o',
    appId: '1:325048551161:ios:d964e0ea2b726560504428',
    messagingSenderId: '325048551161',
    projectId: 'test-liitx',
    storageBucket: 'test-liitx.appspot.com',
    iosClientId: '325048551161-8gq7f0a91j9vgpkcgvs9j1c8cijh71ed.apps.googleusercontent.com',
    iosBundleId: 'com.liitx.testApp.RunnerTests',
  );
}
